{
 "title": "argos - monitoring dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "db", "label": "Bucket", "query": "SHOW DATABASES" },
   {
    "name": "argos_config",
    "label": "Argos Monitors",
    "query": "SHOW TAG VALUES ON \"$db\" FROM \"argos.transaction\" WITH KEY = \"config\""
   }
  ]
 },
 "panels": [
  {
   "title": "argos",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>argos - synthetic monitoring</h1></center>"
   }
  },
  {
   "title": "Transaction Availability",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "argos.transaction",
     "query": "SELECT min(\"success\") FROM \"$db\"..\"argos.transaction\" WHERE $timeFilter GROUP BY time($__interval), \"transaction\" fill(null)",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Endpoints Availability",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "alias": "$tag_transaction - $tag_endpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "endpoint" ], "type": "tag" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "argos.transaction.endpoint",
     "query": "SELECT min(\"success\") FROM \"$db\"..\"argos.transaction.endpoint\" WHERE $timeFilter GROUP BY time($__interval), \"endpoint\", \"transaction\" fill(null)",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_transaction - $tag_endpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "endpoint" ], "type": "tag" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "argos.transaction.endpoint",
     "query": "SELECT mean(\"total_duration\") FROM \"$db\"..\"argos.transaction.endpoint\" WHERE $timeFilter GROUP BY time($__interval), \"endpoint\", \"transaction\" fill(null)",
     "select": [
      [
       { "params": [ "total_duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time To First Byte",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_transaction - $tag_endpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "endpoint" ], "type": "tag" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "argos.transaction.endpoint",
     "query": "SELECT mean(\"first_byte_duration\") FROM \"$db\"..\"argos.transaction.endpoint\" WHERE $timeFilter GROUP BY time($__interval), \"endpoint\", \"transaction\" fill(null)",
     "select": [
      [
       { "params": [ "first_byte_duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}